namespace Test.Chinese.Helpers
{
    public enum MarkType
    {
      
        FullStop,//.
        Comma,//,
        Colon,//;
        SemiColon,//:
        QuestionMark,//?
        ExclamationMark,//!
        Apostrope,//`
        Hyphen,//-
        Dash,//--
        Dots,//....
        SingleQuotationMark,//'
        DoubleQuotationMark,//"
        Parallel,//||
        And,//&
        SwungDash,//~
        Plus,//+
        Minus,//-
        PlusOrMinus,//±
        MutipliedBy,//*
        DividedBy,
        EquelTo,//=
        NotEquelTo,//≠
        ApproximatelyEqual,//≈
        LessThan,//<
        MoreThan,//>
        NotLessThan,//≮ 
        NotMoreThan,//≯
        LessOrEquel,//≤
        MoreOrEquel,//≥
        Percent,//%
        Permill,//‰
        Infinity,//∞
        Root,//√ 
        Since,//∵ 
        Hence,//∴ 
        Pi,//π 
        PerpendicularTo,//⊥
        UnionOf,//∪
        IntersectionOf,//∩
        IntegralOf,//∫
        SummationOf,//∑
        Degree,//° 
        Minute,//′ 
        Second,//〃
        CelsiusSystem,//℃
        OpenBrace,//{ 
        CloseBrace,//}
        OpenParen,//(
        CloseParen,//)
        OpenBracket,//[
        CloseBracket,//]
        ChineseQuestionMark,//？
        ChineseExclamationMark,//！
        ChineseComma,//，
        ChineseFullStop,//。
        ChineseColon,//；
        ChineseSemicolon,//：
        ChineseOpenSingleQuotation,//‘
        ChineseCloseSingleQuotation,//‘
        ChineseOpenDoubleQuotation,//“
        ChineseCloseDoubleQuotation,//“
        SlightPauseMark,//、
        ChineseOpenBrace,//{
        ChineseCloseBrace,//}
        ChineseOpenBrackt,//【
        ChineseCloseBrakt,//】
        ChineseOpenParen,//（
        ChineseCloseParen,//）
        OpenBookTitle,//《
        CloseBookTitle,//》
        Rmb,
        Doller,
        Poun,
        Angle,
        Arc,
        Triangle,
        Circle,
        Power,
        BelongTo,
        NotBelongTo,
        Include,
        BeIncluded,
        EquelMark,
        Derivation,
        Not,
        Any,
        At,
        Hash,
        UnderScode,
        Unknow

    }
}
